// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messageId.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from messageId.proto</summary>
  public static partial class MessageIdReflection {

    #region Descriptor
    /// <summary>File descriptor for messageId.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9tZXNzYWdlSWQucHJvdG8SAnBiKqkBCglNZXNzYWdlSWQSCAoETm9uZRAA",
            "Eg0KB0NTTG9naW4Q0YYDEg0KB1NDTG9naW4Q0oYDEhEKC0NTQWRkRnJpZW5k",
            "EKGNBhIRCgtTQ0FkZEZyaWVuZBCijQYSEQoLQ1NEZWxGcmllbmQQo40GEhEK",
            "C1NDRGVsRnJpZW5kEKSNBhITCg1DU1NlbmRDaGF0TXNnEKWNBhITCg1TQ1Nl",
            "bmRDaGF0TXNnEKaNBkJNCgZjb20ucGJCDk1lc3NhZ2VJZFByb3RvUAFaC3By",
            "b3RvL3BiO3BiogIDUFhYqgICUGLKAgJQYuICDlBiXEdQQk1ldGFkYXRh6gIC",
            "UGJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pb.MessageId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MessageId {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("CSLogin")] Cslogin = 50001,
    [pbr::OriginalName("SCLogin")] Sclogin = 50002,
    /// <summary>
    ///player
    /// </summary>
    [pbr::OriginalName("CSAddFriend")] CsaddFriend = 100001,
    [pbr::OriginalName("SCAddFriend")] ScaddFriend = 100002,
    [pbr::OriginalName("CSDelFriend")] CsdelFriend = 100003,
    [pbr::OriginalName("SCDelFriend")] ScdelFriend = 100004,
    [pbr::OriginalName("CSSendChatMsg")] CssendChatMsg = 100005,
    [pbr::OriginalName("SCSendChatMsg")] ScsendChatMsg = 100006,
  }

  #endregion

}

#endregion Designer generated code
