// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: messageId.proto

package pd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageId int32

const (
	MessageId_None    MessageId = 0
	MessageId_CSLogin MessageId = 50001
	MessageId_SCLogin MessageId = 50002
	// player
	MessageId_CSAddFriend   MessageId = 100001
	MessageId_SCAddFriend   MessageId = 100002
	MessageId_CSDelFriend   MessageId = 100003
	MessageId_SCDelFriend   MessageId = 100004
	MessageId_CSSendChatMsg MessageId = 100005
	MessageId_SCSendChatMsg MessageId = 100006
)

// Enum value maps for MessageId.
var (
	MessageId_name = map[int32]string{
		0:      "None",
		50001:  "CSLogin",
		50002:  "SCLogin",
		100001: "CSAddFriend",
		100002: "SCAddFriend",
		100003: "CSDelFriend",
		100004: "SCDelFriend",
		100005: "CSSendChatMsg",
		100006: "SCSendChatMsg",
	}
	MessageId_value = map[string]int32{
		"None":          0,
		"CSLogin":       50001,
		"SCLogin":       50002,
		"CSAddFriend":   100001,
		"SCAddFriend":   100002,
		"CSDelFriend":   100003,
		"SCDelFriend":   100004,
		"CSSendChatMsg": 100005,
		"SCSendChatMsg": 100006,
	}
)

func (x MessageId) Enum() *MessageId {
	p := new(MessageId)
	*p = x
	return p
}

func (x MessageId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageId) Descriptor() protoreflect.EnumDescriptor {
	return file_messageId_proto_enumTypes[0].Descriptor()
}

func (MessageId) Type() protoreflect.EnumType {
	return &file_messageId_proto_enumTypes[0]
}

func (x MessageId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageId.Descriptor instead.
func (MessageId) EnumDescriptor() ([]byte, []int) {
	return file_messageId_proto_rawDescGZIP(), []int{0}
}

var File_messageId_proto protoreflect.FileDescriptor

const file_messageId_proto_rawDesc = "" +
	"\n" +
	"\x0fmessageId.proto\x12\x02pd*\xa9\x01\n" +
	"\tMessageId\x12\b\n" +
	"\x04None\x10\x00\x12\r\n" +
	"\aCSLogin\x10ц\x03\x12\r\n" +
	"\aSCLogin\x10҆\x03\x12\x11\n" +
	"\vCSAddFriend\x10\xa1\x8d\x06\x12\x11\n" +
	"\vSCAddFriend\x10\xa2\x8d\x06\x12\x11\n" +
	"\vCSDelFriend\x10\xa3\x8d\x06\x12\x11\n" +
	"\vSCDelFriend\x10\xa4\x8d\x06\x12\x13\n" +
	"\rCSSendChatMsg\x10\xa5\x8d\x06\x12\x13\n" +
	"\rSCSendChatMsg\x10\xa6\x8d\x06BM\n" +
	"\x06com.pdB\x0eMessageIdProtoP\x01Z\vproto/pd;pd\xa2\x02\x03PXX\xaa\x02\x02Pd\xca\x02\x02Pd\xe2\x02\x0ePd\\GPBMetadata\xea\x02\x02Pdb\x06proto3"

var (
	file_messageId_proto_rawDescOnce sync.Once
	file_messageId_proto_rawDescData []byte
)

func file_messageId_proto_rawDescGZIP() []byte {
	file_messageId_proto_rawDescOnce.Do(func() {
		file_messageId_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messageId_proto_rawDesc), len(file_messageId_proto_rawDesc)))
	})
	return file_messageId_proto_rawDescData
}

var file_messageId_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messageId_proto_goTypes = []any{
	(MessageId)(0), // 0: pd.MessageId
}
var file_messageId_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messageId_proto_init() }
func file_messageId_proto_init() {
	if File_messageId_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messageId_proto_rawDesc), len(file_messageId_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messageId_proto_goTypes,
		DependencyIndexes: file_messageId_proto_depIdxs,
		EnumInfos:         file_messageId_proto_enumTypes,
	}.Build()
	File_messageId_proto = out.File
	file_messageId_proto_goTypes = nil
	file_messageId_proto_depIdxs = nil
}
